server:
  port: 8085
spring:
  application:
    name: ac_demo
  activiti:
    database-schema-update: true
    check-process-definitions: false
    db-history-used: true
    history-level: full
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sp_activiti7?serverTimezone=Shanghai&useSSL=false&nullCatalogMeansCurrent=true
    url: jdbc:mysql://localhost:3306/sp_activiti7?useSSL=true&nullCatalogMeansCurrent=true&characterEncoding=UTF-8
    username: root
    password: root
  security:
    basic:
      enabled: false
    user:
      name: 111
      password: 111
management:
  endpoints:
    web:
      exposure:
        include: loggers,sessions
logging:
  level:
    org.activiti.engine.impl.persistence.entity: debug
